# Generated by Django 3.0.4 on 2020-03-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catalog',
            new_name='catalog_id',
        ),
    ]
